spring:

  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      username: sa
      password:
      jdbc-url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: {client-id}
            client-secret: {secret-key}
            scope: account_email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  auth:
    secret-key: MYREALTRIP::rakwon.seong@myrealtrip.com
    access-token:
      expiration: 7200 #2시간
    refresh-token:
      expiration: 1209600 #2주